trigger:
  - develop
  - master

name: $(BuildID)
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: buildBack
    steps:
      - task: Bash@3
        displayName: Build
        inputs:
          filePath: 'build.sh'
      - publish: Deploy
        artifact: studo-back-build
- stage: packDocker
  displayName: pack Docker image
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: packBuild
    steps:
      - download: current
        artifact: studo-back-build
      - task: Docker@2
        inputs:
          containerRegistry: 'rtuitlab connection by admin'
          repository: 'rtuitlab/studo-back'
          command: 'buildAndPush'
          Dockerfile: '$(Pipeline.Workspace)/studo-back-build/Dockerfile'
          buildContext: '$(Pipeline.Workspace)/studo-back-build'
          tags: |
            $(Build.BuildId)
            lastest