name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if notIn(variables['Build.SourceBranchName'], 'master', 'develop') }}:
    buildImage: false
    deployService: false
    deployEnvironment: 'no'
    imageTags: 'no'
    serviceName: 'no'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    buildImage: true
    deployService: true
    deployEnvironment: development
    imageTags: |
      $(Build.BuildId)
      develop
    serviceName: studo-develop_back
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildImage: true
    deployService: true
    deployEnvironment: production
    imageTags: |
      $(Build.BuildId)
      latest
    serviceName: studo_back

stages:
- stage: build
  displayName: Build
  jobs:
  - job: buildBack
    steps:
      - task: Bash@3
        displayName: Build
        inputs:
          filePath: 'build.sh'
      - publish: Deploy
        artifact: studo-back-build
- stage: packDocker
  displayName: pack Docker image
  condition: ${{variables.buildImage}}
  jobs:
  - job: packBuild
    steps:
      - download: current
        artifact: studo-back-build
      - task: Docker@2
        inputs:
          containerRegistry: 'rtuitlab connection by admin'
          repository: 'rtuitlab/studo-back'
          command: 'buildAndPush'
          Dockerfile: '$(Pipeline.Workspace)/studo-back-build/Dockerfile'
          buildContext: '$(Pipeline.Workspace)/studo-back-build'
          tags: ${{variables.imageTags}}
- stage: deploy
  displayName: deploy
  condition: ${{variables.deployService}}
  jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      environment: ${{variables.deployEnvironment}}
      strategy:
        runOnce:
          deploy:
            steps:
              - download: none
              - task: SSH@0
                inputs:
                  sshEndpoint: 'swarm manager'
                  runOptions: 'commands'
                  commands: 'docker service update --image rtuitlab/studo-back:$(Build.BuildId) ${{variables.serviceName}}'
                  readyTimeout: '20000'